package com.example.ryeblog.DB;

import androidx.room.ColumnInfo;
import androidx.room.Entity;
import androidx.room.PrimaryKey;

@Entity(tableName="posts")
public class Post {

    // Note that if id == 0, and this is inserted, an id will be autogenerated
    public Post(int id, String username, String title, String text) {
        this.id = id;
        this.username = username;
        this.title = title;
        this.text = text;
    }

    @PrimaryKey(autoGenerate = true)
    @ColumnInfo(name = "id")
    public int id;

    @ColumnInfo(name = "username")
    public String username;

    @ColumnInfo(name = "title")
    public String title;

    @ColumnInfo(name = "text")
    public String text;
}
